07:26:15 PM:DEBUG [logger_base.py:16] Mensaje a nivel debug
07:26:15 PM:INFO [logger_base.py:17] Mensaje a nivel info
07:26:15 PM:WARNING [logger_base.py:18] Mensaje a nivel warninf
07:26:15 PM:ERROR [logger_base.py:19] Mensaje a nivel error
07:26:15 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
06:21:25 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Lucas,
            Apellido:Bay,
            Email: Lbay@mail.com
        
06:27:05 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Lucas,
            Apellido:Bay,
            Email: Lbay@mail.com
        
06:27:05 PM:DEBUG [Persona.py:55] 
            Id Persona: None,
            Nombre: Jose,
            Apellido:Day,
            Email: Jday@mail.com
        
06:35:20 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Lucas,
            Apellido:Bay,
            Email: Lbay@mail.com
        
06:35:20 PM:DEBUG [Persona.py:55] 
            Id Persona: None,
            Nombre: Jose,
            Apellido:Day,
            Email: Jday@mail.com
        
06:35:20 PM:DEBUG [Persona.py:57] 
            Id Persona: 1,
            Nombre: None,
            Apellido:None,
            Email: None
        
07:07:05 PM:DEBUG [conexion.py:25] Conexion exitosa: <connection object at 0x000001B5CC0BC6A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:17:20 PM:DEBUG [conexion.py:25] Conexion exitosa: <connection object at 0x000001B0DB22C6A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:17:20 PM:ERROR [conexion.py:41] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
07:20:16 PM:DEBUG [conexion.py:25] Conexion exitosa: <connection object at 0x000001FB1622C6A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:16 PM:ERROR [conexion.py:41] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
07:20:29 PM:DEBUG [conexion.py:25] Conexion exitosa: <connection object at 0x000001C03C18C6A0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
07:20:29 PM:DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000001C03BE073E0; closed: 0>
